ETAWarrantLookup/Controllers/WarrantController.cs
using ETAWarrantLookup.Models;
using ETAWarrantLookup.ViewModels;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.FileProviders;
using Microsoft.Extensions.Logging;
using Microsoft.VisualBasic.FileIO;

using Newtonsoft.Json;
using NuGet.Packaging.Signing;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.IO;
using System.Linq;
using System.Threading.Tasks;


namespace ETAWarrantLookup.Controllers
{
    public class WarrantController : Controller
    {
        private readonly IMemoryCache _memoryCache;
        private readonly IConfiguration _configuration;
        private readonly ILogger<WarrantController> _logger;


        public WarrantController(IMemoryCache memoryCache, IConfiguration configuration, ILogger<WarrantController> logger)
        {
            _memoryCache = memoryCache;
            _configuration = configuration;
            _logger = logger;

         }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Search()
        {
            WarrantSearchViewModel vm = new WarrantSearchViewModel();

            if(!string.IsNullOrWhiteSpace(HttpContext.Session.GetString("Fname")))
            {
                vm.FirstName = HttpContext.Session.GetString("Fname");
            }

            if (!string.IsNullOrWhiteSpace(HttpContext.Session.GetString("Lname")))
            {
                vm.LastName = HttpContext.Session.GetString("Lname");
            }

            if (!string.IsNullOrWhiteSpace(HttpContext.Session.GetString("Sex")))
            {
                vm.Sex = HttpContext.Session.GetString("Sex");
            }

            if (!string.IsNullOrWhiteSpace(HttpContext.Session.GetString("Race")))
            {
                vm.Race = HttpContext.Session.GetString("Race");
            }

            if (HttpContext.Session.GetString("Court") != null)
            {
                vm.Court = HttpContext.Session.GetString("Court");
            }


            vm.CourtList = await GetCourtDropdownValues();
            vm.SexList = await GetSexDropdownValues();
            vm.RaceList = await GetRaceDropdownValues();        

            return View(vm);
        }

        [HttpGet]
        [Authorize]
        public IActionResult SearchResults(WarrantSearchViewModel vm)
        {
            //retain the search criteria
            HttpContext.Session.SetString("Fname", vm.FirstName ?? string.Empty);
            HttpContext.Session.SetString("Lname", vm.LastName ?? string.Empty);
            HttpContext.Session.SetString("Race", vm.Race ?? string.Empty);
            HttpContext.Session.SetString("Sex", vm.Sex ?? string.Empty);
            HttpContext.Session.SetString("Court", vm.Court ?? string.Empty);


            //filter the data based on query
            //IQueryable<WarrantModel> query = GetWarrants().GetAwaiter().GetResult().ToList() as IQueryable<WarrantModel>;

            var query = GetWarrants().GetAwaiter().GetResult();

            if (!string.IsNullOrWhiteSpace(vm.FirstName))
            {
                query = query.Where(m => m.GFNAME.Contains(vm.FirstName.ToUpper()));
            }
            if (!string.IsNullOrWhiteSpace(vm.LastName))
            {
                query = query.Where(m => m.GLNAME.Contains(vm.LastName.ToUpper()));
            }
            if (!string.IsNullOrWhiteSpace(vm.Court))
            {
                query = query.Where(m => m.GNAME == vm.Court);
            }
            if (!string.IsNullOrWhiteSpace(vm.Race))
            {
                query = query.Where(m => m.GRACE == vm.Race);
            }
            if (!string.IsNullOrWhiteSpace(vm.Sex))
            {
                query = query.Where(m => m.GSEX == vm.Sex);
            }

            var results = query.ToList();

            //IEnumerable<WarrantModel> model = new List<WarrantModel>();

            //iterate over the results and build the details url           
            foreach (var warrant in results)
            {

                warrant.GWARRANTDETAILSURL = Url.Content("~/Warrant/Details" + "?c1=" + warrant.GCASE1 + "&c2=" + warrant.GCASE2 + "&c3=" + warrant.GCASE3 + "&offend=" + warrant.GLNAME);
            }

            return PartialView("SearchResults", results);
        }


        //TODO - use the view model for the parameter
        [HttpGet]
        [Authorize]
        public IActionResult Details(string c1, string c2, string c3, string offend)
        {          
            var data = GetWarrantDetails(c1, c2, c3, offend).GetAwaiter().GetResult();

            return View(data);
        }


        // TODO - this needs to take a view model, why not.
        // This also allows the calling page to know what the query was for the back button on details page
        [Authorize]
        private async Task<IEnumerable<WarrantModel>> GetWarrantDetails(string c1, string c2, string c3, string offend)
        {
            var data = GetWarrants().GetAwaiter().GetResult().ToList();

            var data2 = GetAgencies().GetAwaiter().GetResult().ToList();


            //gname = bco

            // this will retrieve the 1 record that matches the query parameters
            var warrants = 
                data.Where(m => m.GCASE1 == c1)
                .Where(m => m.GCASE2 == c2)
                .Where(m => m.GCASE3 == c3)
                .Where(m => m.GLNAME == offend)
                .ToList();

            if (warrants.Count > 0)
            {
                foreach(var d in warrants)
                {
                    d.COURTPHONE = data2.Where(m => m.BNAME == d.GNAME).FirstOrDefault().BPHONE.ToString();
                }


                // now we need to see if there are others that match.
                var otherWarrants =
                    data.Where(m => m.GLNAME == warrants.First().GLNAME)
                    .Where(m => m.GFNAME == warrants.First().GFNAME)
                    .Where(m => m.GHGT == warrants.First().GHGT)
                    .Where(m => m.GWHT == warrants.First().GWHT)
                    .Where(m => m.GRACE == warrants.First().GRACE)
                    .Where(m => m.GSEX == warrants.First().GSEX);



                warrants.AddRange(otherWarrants.Where(m => m.GCASE != warrants.First().GCASE));
            }

            return warrants;
        }


        
        /// <summary>
        /// Responsible for retrieving unique court values from the data collection
        /// </summary>
        private async Task<IEnumerable<SelectListItem>> GetCourtDropdownValues()
        {
            var cacheKey = "courtddlValues";

            // check if cache entry exists
            if (!_memoryCache.TryGetValue(cacheKey, out IEnumerable<SelectListItem> courtddlValues))
            {

                var data = await GetWarrants();
                var dataList = data.Select(m => m.GNAME).Distinct().ToList();
                dataList.Sort();

                List<SelectListItem> selectListItems = new();

                foreach (var item in dataList)
                {
                    selectListItems.Add(new SelectListItem(item, item));
                }


                //setting up cache options
                var cacheExpiryOptions = new MemoryCacheEntryOptions
                {
                    AbsoluteExpiration = DateTime.Now.AddSeconds(5000),
                    Priority = CacheItemPriority.High,
                    SlidingExpiration = TimeSpan.FromSeconds(2000)
                };
                //setting cache entries
                _memoryCache.Set(cacheKey, selectListItems, cacheExpiryOptions);

                return selectListItems;
            }
            else
            {
                return courtddlValues;
            }
        }


        /// <summary>
        /// Responsible for retrieving unique sex values from the data collection
        /// </summary>
        private async Task<IEnumerable<SelectListItem>> GetSexDropdownValues()
        {
            var cacheKey = "sexddlValues";

            // check if cache entry exists
            if (!_memoryCache.TryGetValue(cacheKey, out IEnumerable<SelectListItem> sexddlValues))
            {

                var data = await GetWarrants();
                var dataList = data.Select(m => m.GSEX).Distinct().ToList();
                dataList.Sort();

                List<SelectListItem> selectListItems = new();

                foreach (var item in dataList)
                {
                    selectListItems.Add(new SelectListItem(item, item));
                }

                //setting up cache options
                var cacheExpiryOptions = new MemoryCacheEntryOptions
                {
                    AbsoluteExpiration = DateTime.Now.AddSeconds(5000),
                    Priority = CacheItemPriority.High,
                    SlidingExpiration = TimeSpan.FromSeconds(2000)
                };
                //setting cache entries
                _memoryCache.Set(cacheKey, selectListItems, cacheExpiryOptions);

                return selectListItems;
            }
            else
            {
                return sexddlValues;
            }
        }

        /// <summary>
        /// Responsible for retrieving unique race values from the data collection
        /// </summary>
        /// <returns></returns>
        private async Task<IEnumerable<SelectListItem>> GetRaceDropdownValues()
        {
            var cacheKey = "raceddlValues";

            // check if cache entry exists
            if (!_memoryCache.TryGetValue(cacheKey, out IEnumerable<SelectListItem> raceDdlValues))
            {

                var data = await GetWarrants();
                var dataList = data.Select(m => m.GRACE).Distinct().ToList();

ETAWarrantLookup/Views/Warrant/Details.cshtml
@model IEnumerable<WarrantModel>

<br/>

@if (@Model.Count() == 0)
{
    <div class="card text-center" style="border-radius:15px">
        <div class="card-header">
            <p>Data Error</p>
        </div>
        <div class="card-body text-center">           
                <p>The details for this warrant cannot be retrieved due to inconsistencies with the record.</p>
        </div>
    </div>
}
else
{
    <div class="card text-center" style="border-radius:15px">
        <div class="card-header">
            <div class="row">
                <div class="col-sm"> <h5>Court Info:</h5> @Model.First().GNAME </div>
                <div class="col-sm"><label>Phone:</label>@Model.First().GPHONE</div>
                <div class="col-sm"> <h5>Police Dept Info:</h5> @Model.First().GCITY </div>
                <div class="col-sm"><label>Phone:</label>@Model.First().COURTPHONE</div>
            </div>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm">
                    <h5>Case #</h5>@Model.First().GCASE
                </div>
                <div class="col-sm">
                    <h5>Defendant Name & Address</h5>
                    <label>@Model.First().GWHOLENAME</label>
                    <label>@Model.First().GADDR</label>
                    <label>@Model.First().GCITY, @Model.First().GSTATE  @Model.First().GZIP5 - @Model.First().GZIP4</label>
                </div>
                <div class="col-sm">
                    <h5>Warrant Date:</h5>
                    <label>@Model.First().GWDATE</label>
                </div>
                <div class="col-sm">
                    <h5>Tag Info:</h5>
                    <label>@Model.First().GTAGST - @Model.First().GTAGNO</label>
                </div>
                <div class="col-sm">
                    <iframe src="https://www.google.com/maps/embed/v1/place?key=AIzaSyA8JTfWH5uw6jVixnmXrxihSHRDuGS63gE&amp;q= @Model.First().GADDR @Model.First().GCITY, @Model.First().GSTATE " allowfullscreen="" width="300" height="225"></iframe>
                </div>
            </div>


        </div>
        <div class="card-footer text-muted">
            <div class="row">
                <div class="col-sm">
                    <input type="button" class="btn btn-info" value="<< Go Back" onclick="history.go(-1)">
                </div>
                <div class="col-sm">
                    <input type="button" class="btn btn-info" value="Print Screen" onclick="window.print();return false;">
                </div>
                <div class="col-sm">
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
    </div>
    <br/>
    <div class="card text-center" style="border-radius:15px">
        <div class="card-header">
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm">
                    <b>Offense Dt</b>
                    <hr />
                    <label>@Model.First().GODATE</label>
                </div>
                <div class="col-sm">
                    <b>DOB</b>
                    <hr />
                    <label>@Model.First().GBDATE</label>
                </div>
                <div class="col-sm">
                    <b>Race</b>
                    <hr />
                    <label>@Model.First().GRACE</label>
                </div>
                <div class="col-sm">
                    <b>Sex</b>
                    <hr />
                    <label>@Model.First().GSEX</label>
                </div>
                <div class="col-sm">
                    <b>Hgt</b>
                    <hr />
                    <label>
                        @string.Format(Model.First().GHGT.Substring(0, 1) + "\' " + Model.First().GHGT.Substring(1) + "\"")
                    </label>
                </div>
                <div class="col-sm">
                    <b>Wgt</b>
                    <hr />
                    <label>@Model.First().GWHT</label>
                </div>
                <div class="col-sm">
                    <b>Hair</b>
                    <hr />
                    <label>@Model.First().GHAIR</label>
                </div>
                <div class="col-sm">
                    <b>Eyes</b>
                    <hr />
                    <label>@Model.First().GEYES</label>
                </div>
                <div class="col-sm">
                    <b>Age</b>
                    <hr />
                    <label>
                        @Model.First().GAGE
                    </label>
                </div>
            </div>
        </div>
        <div class="card-footer text-muted">
            <div class="row justify-content-start">
                <div class="col-sm-2">
                    <b>Warrant Offense:</b>
                </div>
                <div class="col-sm-10">
                    @foreach (var warrant in Model)
                    {
                        <div class="row">
                            <label style="color:red"> (@warrant.GODATE) - @warrant.GOFFD</label>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
}

ETAWarrantLookup/Views/Warrant/Search.cshtml
@model ETAWarrantLookup.ViewModels.WarrantSearchViewModel;

@{
    ViewData["Title"] = "Warrant Search";

}

<br/>

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "searchForm" }))
{
    @Html.AntiForgeryToken()
    <div class="card" style="border-radius:15px;">
        <div class="card-body">
            <div class="row">
                <div class="col-sm">
                    <label for="LastName" class="form-label">Last Name</label>
                    @Html.EditorFor(m => m.LastName, new { htmlAttributes = new { @class = "form-control", @style = "text-transform:uppercase" } })
                </div>
                <div class="col-sm">
                    <label for="FirstName" class="form-label">First Name</label>
                    @Html.EditorFor(m => m.FirstName, new { htmlAttributes = new { @class = "form-control", @style = "text-transform:uppercase" } })
                </div>
                <div class="col-sm">
                    <label for="Race" class="form-label">Race</label>
                    @Html.DropDownListFor(m => m.Race, Model.RaceList,"--Select--", new{ @class= "form-control"})
                </div>
                <div class="col-sm">
                    <label for="Sex" class="form-label">Sex</label>
                    @Html.DropDownListFor(m => m.Sex, Model.SexList,"--Select--", new{ @class= "form-control"})
                </div>
                <div class="col-sm">
                    <label for="Court" class="form-label">Court</label>
                    @Html.DropDownListFor(m => m.Court, Model.CourtList,"--Select--", new{ @class= "form-control"})
                </div>
                <div class="col-sm">
                    <label class="form-label">  </label>
                    <input id="btnSearch" type="button" value="Query" class="btn btn-info form-control" />
                </div>
            </div>
            <div class="row">
            </div>
        </div>
    </div>
}

<br/>

<div class="card" style="border-radius:15px;">
    <div class="card-body">
        <div id="searchResults"></div>
    </div>
</div>


@section scripts
{
<script type="text/javascript">
        var url = '@Url.Action("SearchResults", "Warrant")';
    $('#btnSearch').click(function() {
      var formData = $("#searchForm").serialize();
      $('#searchResults').load(url, formData);
      return false; // prevent the default submit action
    })

</script>
}

ETAWarrantLookup/Views/Warrant/SearchResults.cshtml
@model IEnumerable<WarrantModel>

<script>
    document.querySelectorAll(".mvc-grid").forEach(element => new MvcGrid(element));
</script>

@(Html.Grid(Model).Build(columns =>
        {
            columns.Add(m => "<a href=" + m.GWARRANTDETAILSURL + ">"+ m.GCASE +"</a>").Titled("Case #").IsEncoded=false;
            columns.Add(m => m.GWHOLENAME).Titled("Last, First");
            columns.Add(m => m.GHGT.Substring(0,1) + "\' " + m.GHGT.Substring(1) + "\"").Titled("Hgt");
            columns.Add(m => m.GWHT + " lbs").Titled("Wgt");
            columns.Add(m => m.GEYES).Titled("Eyes");
            columns.Add(m => m.GHAIR).Titled("Hair");
            columns.Add(m => m.GRACE).Titled("Race");
            columns.Add(m => m.GSEX).Titled("Sex");
            columns.Add(m => m.GBDATE).Titled("DOB");
            columns.Add(m => m.GCITY).Titled("City");
        })
         .Using(GridFilterMode.Header)
    .Empty("No data found")
    //.Filterable()
    //.Sortable()
    @* .Pageable(pager =>
    {
        pager.PageSizes = new Dictionary<Int32, String> { { 0, "All" }, { 2, "2" }, { 4, "4" } };
        pager.ShowPageSizes = true;
        pager.PagesToDisplay = 1;
        pager.CurrentPage = 1;
        pager.RowsPerPage = 5;
    })*@

        )